### ISSUE TITLE
creation of archive leads to error

### ISSUE THREAD

**Issue by rrbn** [ilifau/TestArchiveCreator#1]
failed to open stream: Datei oder Verzeichnis nicht gefunden

Stacktrace:
#9 Whoops\Exception\ErrorException in /srv/www/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/TestArchiveCreator/classes/class.ilTestArchiveCreator.php:482
#8 sha1_file in /srv/www/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/TestArchiveCreator/classes/class.ilTestArchiveCreator.php:482
#7 ilTestArchiveCreator:writeIndexFiles in /srv/www/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/TestArchiveCreator/classes/class.ilTestArchiveCreator.php:89
#6 ilTestArchiveCreator:createArchive in /srv/www/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/TestArchiveCreator/classes/class.ilTestArchiveCreatorSettingsGUI.ph$
#5 ilTestArchiveCreatorSettingsGUI:createArchive in /srv/www/ilias/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/TestArchiveCreator/classes/class.ilTestArchiveCreatorSet$
#4 ilTestArchiveCreatorSettingsGUI:executeCommand in /srv/www/ilias/Services/UICore/classes/class.ilCtrl.php:188
#3 ilCtrl:forwardCommand in /srv/www/ilias/Services/UIComponent/classes/class.ilUIPluginRouterGUI.php:36
#2 ilUIPluginRouterGUI:executeCommand in /srv/www/ilias/Services/UICore/classes/class.ilCtrl.php:188
#1 ilCtrl:forwardCommand in /srv/www/ilias/Services/UICore/classes/class.ilCtrl.php:150
#0 ilCtrl:callBaseClass in /srv/www/ilias/ilias.php:21

**Comment by fneumann** [comment]
Also added a loggin of phantomjs calls in version 1.0.2. That may help to find what's wrong with the PDF generation.
