### ISSUE TITLE
ilDatePresentation::formatDate() must be an instance of ilDateTime, null given

### ISSUE THREAD

**Issue by fsesterh** [ilifau/TestArchiveCreator#10]
Hi,

on one of our tests I get this error when accessing the export tab. The error message points to a class of this plugin, which is why I post this here. Hope this is the right place.

TypeError thrown with message "Argument 1 passed to ilDatePresentation::formatDate() must be an instance of ilDateTime, null given, called in /var/www/ilias_ea_f01/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/TestArchiveCreator/classes/class.ilTestArchiveCreatorSettingsGUI.php on line 108"

Stacktrace:
#12 TypeError in /var/www/ilias_ea_f01/Services/Calendar/classes/class.ilDatePresentation.php:127
#11 ilDatePresentation:formatDate in /var/www/ilias_ea_f01/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/TestArchiveCreator/classes/class.ilTestArchiveCreatorSettingsGUI.php:108
#10 ilTestArchiveCreatorSettingsGUI:modifyExportToolbar in /var/www/ilias_ea_f01/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/TestArchiveCreator/classes/class.ilTestArchiveCreatorUIHookGUI.php:111
#9 ilTestArchiveCreatorUIHookGUI:modifyExportToolbar in /var/www/ilias_ea_f01/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/TestArchiveCreator/classes/class.ilTestArchiveCreatorUIHookGUI.php:46
#8 ilTestArchiveCreatorUIHookGUI:modifyGUI in /var/www/ilias_ea_f01/Services/UIComponent/Tabs/classes/class.ilTabsGUI.php:457
#7 ilTabsGUI:__getHTML in /var/www/ilias_ea_f01/Services/UIComponent/Tabs/classes/class.ilTabsGUI.php:405
#6 ilTabsGUI:getSubTabHTML in /var/www/ilias_ea_f01/Services/UICore/classes/class.ilTemplate.php:682
#5 ilTemplate:getTabsHTML in /var/www/ilias_ea_f01/Services/UICore/classes/class.ilTemplate.php:515
#4 ilTemplate:show in /var/www/ilias_ea_f01/Services/Repository/classes/class.ilRepositoryGUI.php:351
#3 ilRepositoryGUI:show in /var/www/ilias_ea_f01/Services/Repository/classes/class.ilRepositoryGUI.php:310
#2 ilRepositoryGUI:executeCommand in /var/www/ilias_ea_f01/Services/UICore/classes/class.ilCtrl.php:210
#1 ilCtrl:forwardCommand in /var/www/ilias_ea_f01/Services/UICore/classes/class.ilCtrl.php:175
#0 ilCtrl:callBaseClass in /var/www/ilias_ea_f01/ilias.php:20

**Comment by iFadi** [comment]
we fixed this issue bei replacing the line 108 with this code in the class ilTestArchiveCreatorSettingsGUI.php:

`$text .= sprintf($this->plugin->txt('tb_archive_planned'), ilDatePresentation::formatDate(new ilDateTime($this->settings->schedule)));`

**Comment by fneumann** [comment]
I fixed the problem slightly different. The schedule must be a date object or null. So I added an isset() condition in the line and made the date input for planned archive creations required.
