### ISSUE TITLE
Archive creation crashes because of getTestStyleLocation having been removed from ilTestObj in Ilias 7.8

### ISSUE THREAD

**Issue by sbaecker** [ilifau/TestArchiveCreator#13]
Error thrown with message "Call to undefined method ilObjTest::getTestStyleLocation()"

Stacktrace:
#10 Error in /var/www/fb2-anglistik-clone/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/TestArchiveCreator/classes/class.ilTestArchiveCreatorHTML.php:58
#9 ilTestArchiveCreatorHTML:initMainTemplate in /var/www/fb2-anglistik-clone/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/TestArchiveCreator/classes/class.ilTestArchiveCreatorHTML.php:37
#8 ilTestArchiveCreatorHTML:__construct in /var/www/fb2-anglistik-clone/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/TestArchiveCreator/classes/class.ilTestArchiveCreator.php:126
#7 ilTestArchiveCreator:initCreation in /var/www/fb2-anglistik-clone/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/TestArchiveCreator/classes/class.ilTestArchiveCreator.php:80
#6 ilTestArchiveCreator:createArchive in /var/www/fb2-anglistik-clone/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/TestArchiveCreator/classes/class.ilTestArchiveCreatorSettingsGUI.php:397
#5 ilTestArchiveCreatorSettingsGUI:createArchive in /var/www/fb2-anglistik-clone/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/TestArchiveCreator/classes/class.ilTestArchiveCreatorSettingsGUI.php:178
#4 ilTestArchiveCreatorSettingsGUI:executeCommand in /var/www/fb2-anglistik-clone/Services/UICore/classes/class.ilCtrl.php:217
#3 ilCtrl:forwardCommand in /var/www/fb2-anglistik-clone/Services/UIComponent/classes/class.ilUIPluginRouterGUI.php:40
#2 ilUIPluginRouterGUI:executeCommand in /var/www/fb2-anglistik-clone/Services/UICore/classes/class.ilCtrl.php:217
#1 ilCtrl:forwardCommand in /var/www/fb2-anglistik-clone/Services/UICore/classes/class.ilCtrl.php:178
#0 ilCtrl:callBaseClass in /var/www/fb2-anglistik-clone/ilias.php:23

Method in question has been removed with this commit:
https://github.com/ILIAS-eLearning/ILIAS/commit/8a944ff3990433904b3e71197f32802b3fce0651

Commenting out line 58 in class.ilTestArchiveCreatorHTML.php seems to be the right choice, but I'm not sure of any possible side effects.

**Comment by mglaubitz** [comment]
Hi there, we have run into the same error. Is there any news?

@fneumann Is it ok, to simply remove the suggested line that fetches the test style or do you see any problems?

**Comment by fneumann** [comment]
Thanks for the hint. Removing the line is ok because ta.css is now included via LESS in the Delos style. I pushed the fix.
