### ISSUE TITLE
Call to undefined method ilObjTest::getPassFinishDate() ILIAS 5.3.18

### ISSUE THREAD

**Issue by pawohl** [ilifau/TestArchiveCreator#6]
It seems that 469d9a1dd32d57532f38d3cfb32421c0b9e1d952 is also required for ILIAS 5.3. https://github.com/ILIAS-eLearning/ILIAS/commit/a57a64077598616047486772471a2d61753ce2f4#diff-b4d9c555597399e09c310e6c1e3256d5L8379 removed `getPassFinishDate()` in the `release_5-3` branch.

**Comment by pawohl** [comment]
We also had to set `export QT_QPA_PLATFORM=offscreen` in order to get phantomjs to start and to render all images.

**Comment by fneumann** [comment]
Thanks for the hint! I cheery-picked the fix and commited it as version 1.2.2 to the master branch.
