### ISSUE TITLE
ILIAS 6xx Update/Support

### ISSUE THREAD

**Issue by iFadi** [ilifau/TestArchiveCreator#9]
Is there an ILIAS 6xx version of this plugin or any future plans to add support to ILIAS 6xx? Thx

**Comment by fneumann** [comment]
Sorry, an ILIAS 6 version is not yet released. AT FAU we plan to update directly from ILIAS 5.4 to ILIAS 7 in 2022, therefore we will at least create an ILIAS 7 version this year. So far you are the first to ask for an ILIAS 6 version. Would you like help us creating it by testing a beta version and reporting bugs? I just created a dev-ilias6 branch and inreased the supported ILIAS version there. The installation went well, but a call on the test export tab brought first errors with the changed template system in ILIAS 6.

**Comment by iFadi** [comment]
Yes, i will be glad to help. I'll test it on our ILIAS6-Dev installation, and report back.

**Comment by sbaecker** [comment]
We are also planning to upgrade to ILIAS 7 in early 2022. So I also would be glad to help with testing on our ILIAS 7 testbed and reporting bugs.

**Comment by iFadi** [comment]
Our Uni also decided to upgrade directly from ILIAS 5.4.x to ILIAS 7.x.x in 2022, so unfortunately we will skip ILIAS 6, and therefore will not be able to test it for ILIAS 6.

**Comment by fneumann** [comment]
The plugin is now available for ILIAS 7 in the new default branch main-ilias7. There were two refactorings needed due to the ILIAS page layout revision. Perhaps it's possible to extend the minimum ILIAS version back to ILIAS 6, but I will focus on the support for ILIAS 7.
